### ISSUE TITLE
ChainMap instead of copying and updating dictionaries

### ISSUE THREAD

**Issue by alysivji** [busy-beaver-dev/busy-beaver#110]
As a developer, I have a preference for using Idiomatic Python and want to refactor adapters to use `ChainMap`.

I was rewatching Raymond Hettinger's [Transforming Code into Beautiful, Idiomatic Python](https://youtu.be/OSGv2VnC0go) and realized we should be using [ChainMap](https://docs.python.org/3/library/collections.html#collections.ChainMap) instead of copying and updating dictionaries. This is most prevalent in the adapters that have been written.

Go thru and find all instances of `dict.copy()` and `dict(item)`; refactor to use ChainMap.

**Comment by dansdevelopments** [comment]
I think I've got this one. Submitting a PR

**Comment by dansdevelopments** [comment]
I only changed the adapters scripts. I don't see any other occurrences of `.copy`, and apart from one line in `/blueprints/slack/slash_command.py` where we see a dictionary created   `data = dict(request.form)` but then it isn't modified, I don't see any occurrences of `dict(item)` outside of tests. 

I don't know if the intent is to change the tests as well, or if we need to worry about type hints in method definitions. Hopefully my PR meets the need. If not, I'm happy to keep working on it.
