### ISSUE TITLE
Improve Deployment Process

### ISSUE THREAD

**Issue by alysivji** [busy-beaver-dev/busy-beaver#119]
As a repository administration that merges code into `master`, I do not want to `ssh` into the server to redeploy changes to our `docker-compose.prod.yml`.

We need to fully automate the deploy so that no matter what changes, we deploy without errors. This is not my area of expertise, but ansible and/or k8s seem like possible solutions.

**Comment by virogenesis** [comment]
Where is this hosted Aly ?

**Comment by jdolitsky** [comment]
@alysivji @virogenesis I'm happy to help with this as well, please ping me in slack

**Comment by alysivji** [comment]
@virogenesis @jdolitsky 

I will reach out over the next few weeks. Want to get a couple features out before reinvestigating deployment.

Thanks!

**Comment by alysivji** [comment]
We have moved to Kubernetes! WOOT WOOT!

Still deploying manually, but that's another ticket.
