### ISSUE TITLE
Make shared calendar for all Python events in Chicagoland

### ISSUE THREAD

**Issue by rafmagns-skepa-dreag** [busy-beaver-dev/busy-beaver#121]
It would be great to have a shared Google calendar that I can import. This could also be available on the ChiPy website. Should probably include ChiPy, PyLadies, and PyData events

**Comment by alysivji** [comment]
https://developers.google.com/calendar/auth

**Comment by alysivji** [comment]
The calendar is available at WindyCityPython.

Code to sync calendars is private, might open-source it later. Thanks @rafmagns-skepa-dreag for the idea!
