### ISSUE TITLE
setting up dev on windows

### ISSUE THREAD

**Issue by ryansmccoy** [busy-beaver-dev/busy-beaver#128]
As a developer using windows, I want to setup the Development Environment.

**Comment by ryansmccoy** [comment]
https://help.github.com/en/articles/dealing-with-line-endings

**Comment by alysivji** [comment]
Would love to have somebody look into this. I think a lot of this had to do with Windows not being able to use `Makefile`

https://chocolatey.org/ is a workaround

**Comment by ryansmccoy** [comment]
> Would love to have somebody look into this. I think a lot of this had to do with Windows not being able to use `Makefile`
> 
> https://chocolatey.org/ is a workaround

With changes made by Ray (if I remember correctly, which included grep and awk, among other things), I think choco route is no longer an option.
