### ISSUE TITLE
Investigate alternative release workflow

### ISSUE THREAD

**Issue by alysivji** [busy-beaver-dev/busy-beaver#151]
As a developer, I would like to have a nice release workflow

Right now everything that gets merged into master gets deployed. This is good, but also not good. It would be good to cut releases. Investigate a good pattern.

**Comment by eswan18** [comment]
I think there are lots of reasonable ways to do this, but in general I'd recommend Git Flow. The high-level summary is that new features are implemented in their own branches and then, when approved, merged to a single *develop* branch. When you're thinking of making a new release, make a branch off *develop* named for the release (eg 2.7) and when the release is fully stable, merge it to master. I use this workflow at work and have found it extremely useful.

https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow

**Comment by alysivji** [comment]
I think Gitflow is awesome, but it seems too complex for a simple web app. Ended up keeping trunk-based development and I set up Travis job to build a new image when cutting a release from `master` using the GitHub interface.
