### ISSUE TITLE
Refactor GitHub Summary feature slash commands

### ISSUE THREAD

**Issue by alysivji** [busy-beaver-dev/busy-beaver#155]
As a developer, I like to keep logic out of my views. Refactoring the GitHub slash commands: `/busybeaver connect`, `/busybeaver reconnect`, `/busybeaver disconnect` so that the views contain no logic (ala `/busybeaver events`)

**Comment by BinSquare** [comment]
I can take on this one. 

Do you envision refactoring [slash_command.py](https://github.com/busy-beaver-dev/busy-beaver/blob/ad1c699325382f167fd328469825956baf3bc709/busy_beaver/blueprints/slack/slash_command.py) by tacking on a workflow.py in [github summary?](https://github.com/busy-beaver-dev/busy-beaver/tree/ad1c699325382f167fd328469825956baf3bc709/busy_beaver/apps/github_summary)

**Comment by alysivji** [comment]
That's what I was thinking.

I'm trying to balance keeping modules small versus keeping things together. If the `workflow.py` file feels crowded, please feel free to move. No right answer, it's about figuring out what works best.

**Comment by BinSquare** [comment]
Hey @alysivji!

Here is the commit [1](https://github.com/BinSquare/busy-beaver/commit/3292f99728e943aacb7b09f64055e6732b90e49d) to refactor slash_command.py and [2](https://github.com/BinSquare/busy-beaver/commit/aeed793fe38394122196cd3bcc59ba98669a1617) of the new workflow.py.

Am I in the right direction and any changes I should make before I move ahead?

**Comment by alysivji** [comment]
Looking good! I would maybe refactor `check_account_existing` to return a boolean as that's closer to the behavior we expect versus returning text and comparing it to something else

**Comment by BinSquare** [comment]
Hey @alysivji 

Touching bases again for style adjustments and whatnot, here is the  [refactored slash_command.py](https://github.com/BinSquare/busy-beaver/blob/master/busy_beaver/blueprints/slack/slash_command.py) and the logical functions are now in [github workflow.py](https://github.com/BinSquare/busy-beaver/blob/master/busy_beaver/apps/github_summary/workflow.py).

Any thoughts/heads up before I run the tests? 

Note, that I am returning Nonetype into create_github_account_attachment(state) as part of the refactoring effort when an account exists.

**Comment by alysivji** [comment]
Do you mind opening a Pull Request? It will make it easier to understand the changes you made

On top of running tests work, I would manually confirm that you can create an account using slash commands.

**Comment by BinSquare** [comment]
Oh my goodness! Completely forgot about this, much apologies!

**Comment by alysivji** [comment]
No worries at all! I've been reading a book on Design Patterns and learned a new way to simplify a lot of this logic!

Hope you are doing well! =D

**Comment by BinSquare** [comment]
> No worries at all! I've been reading a book on Design Patterns and learned a new way to simplify a lot of this logic!
> 
> Hope you are doing well! =D

I am! Been away from Chicago but I hope to find time to actually contribute something meaningful to this project soon!
