### ISSUE TITLE
Integrate with YouTube API

### ISSUE THREAD

**Issue by alysivji** [busy-beaver-dev/busy-beaver#56]
ChiPy has a [YouTube channel](https://www.youtube.com/channel/UCT372EAC1orBOSUd2fsA8WA).

* Should automate a flow that shares new videos automatically
* Decide on how we want to space out sharing of content

https://stackoverflow.com/questions/18953499/youtube-api-to-fetch-all-videos-on-a-channel

### Subissues

- [x] [#94 Initial work for integration with YouTube API](https://github.com/busy-beaver-dev/busy-beaver/pull/94)
- [ ] [#146 Enable YouTube Feature](https://github.com/busy-beaver-dev/busy-beaver/issues/146)

**Comment by thornycrackers** [comment]
I'll take this one

**Comment by alysivji** [comment]
We already have #146 ; can just track there
