### ISSUE TITLE
Register for ChiPy events thru Slack

### ISSUE THREAD

**Issue by alysivji** [busy-beaver-dev/busy-beaver#61]
Need to figure out the best way to integrate with existing services. This would be a cool slash command

https://api.slack.com/slash-commands

**Comment by tathagata** [comment]
related: https://github.com/chicagopython/chipy.org/issues/184

**Comment by alysivji** [comment]
Busy Beaver's focus has changed to be a community engagement platform. We can provide links for folks to RSVP. Lots easier to deal with.
