### ISSUE TITLE
Enable Slack workspace users to toggle features

### ISSUE THREAD

**Issue by alysivji** [busy-beaver-dev/busy-beaver#89]
Busy-Beaver should only post in channels that it belongs to. This allows admins to remove Busy-Beaver by kicking it out of channels.

A front-end with configuration settings for each of the features can also solve the same problem, but front-end resources are scarce. Hopefully, this will change soon; I need to do outreach in a Chicago JavaScript community. 

Muting Busy-Beaver by kicking it out of a room is a good workaround for a single tenant use case in a single tenant workspace.

**Comment by mercedesb** [comment]
If you have an API ready to go, happy to make a frontend for this

**Comment by alysivji** [comment]
Thank you for helping out with this feature!

Right now I'm working on multi-tenancy to enable other Slack workspaces to install and piggyback off my hacked together backend. Enabling users to log in and toggle features has moved higher up in the backlog.

Is it okay if I ping you in a few weeks once the backend for the frontend has been sketched out? Have not yet created a `/login` endpoint

**Comment by mercedesb** [comment]
👍 👍

**Comment by alysivji** [comment]
Superceeded by #258
